### ISSUE TITLE
Facebook icon not showing on bottom of site

### ISSUE THREAD

**Issue by Honoluluskye** [iHub/ocsdnet-repo#2]
Facebook sharing icon not loading on my mac at the bottom of http://ocsdnet.org/project-soha-extended-a-helping-handand-we-reached-out-and-grasped-it/

I also don't see any of the sharing links for the blog.

Seems like it's loading on JJ's comp but it's not showing on my comp.

**Comment by kiokomw** [comment]
Facebook icon not showing - tested with other devices and users, the icon shows

**Comment by kiokomw** [comment]
Facebook icon not showing - tested with other devices and users, the icon shows
