### ISSUE TITLE
Subscribe on home page not working

### ISSUE THREAD

**Issue by Honoluluskye** [iHub/ocsdnet-repo#8]
The subscribe field at the footer of the home page is not working when trying to click the submit button. Please also confirm that it goes straight into the Mail Chimp OCSDNet account. 

Mail Chimp Log-ins: OCSDNet
Password: OpenScience%

**Comment by kiokomw** [comment]
Fixing underway

**Comment by kiokomw** [comment]
This bug resolved changes being committed to git.
